publish_to: none

name: player_launcher
description: Player launcher URI protocol handler utility.
version: 2.0.0
homepage: https://github.com/Zekfad/player_launcher
repository: https://github.com/Zekfad/player_launcher
issue_tracker: https://github.com/Zekfad/player_launcher/issues

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dev_dependencies:
  zekfad_lints: ^2.2.0

dependencies:
  collection: ^1.17.1
  ffi: ^2.0.1
  path: ^1.8.3
  win32: ^5.12.0
  win32_registry: ^2.1.0
